name: qfpy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - numba
  - scikit-learn
  - tensorflow
  - umap-learn
  - ta-lib
  - pip
  - pip:
    - -r requirements.txt